apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1 # how many Pods you wnat to create?
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers: # Create Pod
      - name: mongodb
        image: mongo:4.2.20-bionic
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongo-secret
              key: mongo-password

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector: # forward the request to pod
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017 # port of container deployment (containerPort)
